HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
    HHHHHHHHHHHKKKKKKKKK           KKKKKKKKKHHHHHHHHHH
    UUUUUUUUUUUU                          UUUUUUUUUUUU
    YYYYYYYYY                                YYYYYYYYY
    YYYYY           @@@           @@@            YYYYY
    YYYYY                   бб                   YYYYY
    YYYYYYYYY            --_  _--            YYYYYYYYY
    UUUUUUUUUUUU            ‾‾            UUUUUUUUUUUU
    HHHHHHHHHHHKKKKKKKKK          HHHHHHHHHHHKKKKKKKKK
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH